title: Canberra Girls' Programming Network
description: &description Canberra branch of the Girls' Programming Network
author: Canberra GPN
url: https://testcbrgpn.github.io
logo: /static/img/gpn.png
github: &github https://github.com/canberragpn
about: *description
urls:
    - text: Home
      url: /
      icon: fa-home
    - text: News
      url: /news/
      icon: fa-comments
      layout: post
    - text: About
      url: /about/
      icon: fa-child
    - text: Register
      url: /register/
      icon: fa-group
    - text: Workshops
      url: /workshops/
      icon: fa-desktop
    - text: Contact
      url: /contact/
      icon: fa-envelope

social:
    - icon: fa-facebook
      link: 'http://www.facebook.com/canberagpn'
    - icon: fa-github
      link: *github

enableTags: true
tagarray: []

baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/news/page:num/"
permalink: pretty
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
